//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;words&gt;
        ///  
        ///  &lt;word val=&quot;Backup software&quot;/&gt;
        ///
        ///  &lt;word val=&quot;Backup type&quot;/&gt;
        ///  &lt;word val=&quot;Mirror&quot;/&gt;
        ///  &lt;word val=&quot;Differential&quot;/&gt;
        ///
        ///  &lt;word val=&quot;CryptoSoft information&quot;/&gt;
        ///  &lt;word val=&quot;Cryptosoft location&quot;/&gt;
        ///  &lt;word val=&quot;Extensions to crypt &quot;/&gt;
        ///  &lt;word val=&quot;Add&quot;/&gt;
        ///
        ///  &lt;word val=&quot;Backup information&quot;/&gt;
        ///  &lt;word val=&quot;Name&quot;/&gt;
        ///  &lt;word val=&quot;Source repository&quot;/&gt;
        ///  &lt;word val=&quot;Mirror repository&quot;/&gt;
        ///  &lt;word val=&quot;Target repository&quot;/&gt;
        ///
        ///  &lt;word val=&quot;Run&quot;/&gt;
        ///
        ///  &lt;word val=&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;words&gt;
        ///
        ///  &lt;word val=&quot;Logiciel de sauvegarde&quot;/&gt;
        ///
        ///  &lt;word val=&quot;Type de sauvegarde&quot;/&gt;
        ///  &lt;word val=&quot;Miroir&quot;/&gt;
        ///  &lt;word val=&quot;Differentielle&quot;/&gt;
        ///
        ///  &lt;word val=&quot;Informations CryptoSoft&quot;/&gt;
        ///  &lt;word val=&quot;Emplacement du logiciel&quot;/&gt;
        ///  &lt;word val=&quot;Extensions à crypter&quot;/&gt;
        ///  &lt;word val=&quot;Ajouter&quot;/&gt;
        ///
        ///  &lt;word val=&quot;Information de sauvegarde&quot;/&gt;
        ///  &lt;word val=&quot;Nom&quot;/&gt;
        ///  &lt;word val=&quot;Dossier source&quot;/&gt;
        ///  &lt;word val=&quot;Dossier miroir&quot;/&gt;
        ///  &lt;word val=&quot;Dossier cible&quot;/&gt;
        ///
        ///  &lt;word val=&quot;Lanc [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
    }
}
